"""new

Revision ID: 20eb2acceaf2
Revises: e49af1b780d1
Create Date: 2023-11-24 17:43:03.767853

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20eb2acceaf2'
down_revision = 'e49af1b780d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shorts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quantity', sa.Integer(), nullable=True))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('quantity')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quantity', sa.INTEGER(), nullable=True))

    with op.batch_alter_table('shorts', schema=None) as batch_op:
        batch_op.drop_column('quantity')

    # ### end Alembic commands ###
