"""more tables

Revision ID: 2dd423f93768
Revises: 423c791ba0a2
Create Date: 2023-11-17 19:50:28.714235

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2dd423f93768'
down_revision = '423c791ba0a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shirts', schema=None) as batch_op:
        batch_op.drop_index('ix_shirts_description')
        batch_op.create_index(batch_op.f('ix_shirts_description'), ['description'], unique=False)
        batch_op.drop_index('ix_shirts_shirt_name')
        batch_op.create_index(batch_op.f('ix_shirts_shirt_name'), ['shirt_name'], unique=False)

    with op.batch_alter_table('shorts', schema=None) as batch_op:
        batch_op.drop_index('ix_shorts_description')
        batch_op.create_index(batch_op.f('ix_shorts_description'), ['description'], unique=False)
        batch_op.drop_index('ix_shorts_shorts_name')
        batch_op.create_index(batch_op.f('ix_shorts_shorts_name'), ['shorts_name'], unique=False)

    with op.batch_alter_table('trousers', schema=None) as batch_op:
        batch_op.drop_index('ix_trousers_description')
        batch_op.create_index(batch_op.f('ix_trousers_description'), ['description'], unique=False)
        batch_op.drop_index('ix_trousers_trousers_name')
        batch_op.create_index(batch_op.f('ix_trousers_trousers_name'), ['trousers_name'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trousers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_trousers_trousers_name'))
        batch_op.create_index('ix_trousers_trousers_name', ['trousers_name'], unique=False)
        batch_op.drop_index(batch_op.f('ix_trousers_description'))
        batch_op.create_index('ix_trousers_description', ['description'], unique=False)

    with op.batch_alter_table('shorts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_shorts_shorts_name'))
        batch_op.create_index('ix_shorts_shorts_name', ['shorts_name'], unique=False)
        batch_op.drop_index(batch_op.f('ix_shorts_description'))
        batch_op.create_index('ix_shorts_description', ['description'], unique=False)

    with op.batch_alter_table('shirts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_shirts_shirt_name'))
        batch_op.create_index('ix_shirts_shirt_name', ['shirt_name'], unique=False)
        batch_op.drop_index(batch_op.f('ix_shirts_description'))
        batch_op.create_index('ix_shirts_description', ['description'], unique=False)

    # ### end Alembic commands ###
