"""short

Revision ID: 2ffd32c63083
Revises: 88db569f6745
Create Date: 2023-11-26 14:23:03.059967

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ffd32c63083'
down_revision = '88db569f6745'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shorts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shorts_name', sa.String(length=64), nullable=True),
    sa.Column('description', sa.String(length=124), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('img', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('shorts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_shorts_description'), ['description'], unique=False)
        batch_op.create_index(batch_op.f('ix_shorts_shorts_name'), ['shorts_name'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shorts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_shorts_shorts_name'))
        batch_op.drop_index(batch_op.f('ix_shorts_description'))

    op.drop_table('shorts')
    # ### end Alembic commands ###
