"""picture column in user

Revision ID: 497760efe526
Revises: fdd3f94a5811
Create Date: 2023-11-21 12:22:16.493913

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '497760efe526'
down_revision = 'fdd3f94a5811'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('profile_img',
               existing_type=sa.VARCHAR(length=1440),
               type_=sa.String(length=20),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('profile_img',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=1440),
               existing_nullable=True)

    # ### end Alembic commands ###
