"""added img col

Revision ID: 6fbf586df8eb
Revises: b9445d5d54b9
Create Date: 2023-11-26 11:40:33.077997

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6fbf586df8eb'
down_revision = 'b9445d5d54b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shirts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shirt_name', sa.String(length=64), nullable=True),
    sa.Column('description', sa.String(length=124), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('img', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('shirts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_shirts_description'), ['description'], unique=False)
        batch_op.create_index(batch_op.f('ix_shirts_shirt_name'), ['shirt_name'], unique=False)

    op.create_table('shorts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shorts_name', sa.String(length=64), nullable=True),
    sa.Column('description', sa.String(length=124), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('img', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('shorts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_shorts_description'), ['description'], unique=False)
        batch_op.create_index(batch_op.f('ix_shorts_shorts_name'), ['shorts_name'], unique=False)

    op.create_table('trousers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trousers_name', sa.String(length=64), nullable=True),
    sa.Column('description', sa.String(length=124), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('img', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('trousers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_trousers_description'), ['description'], unique=False)
        batch_op.create_index(batch_op.f('ix_trousers_trousers_name'), ['trousers_name'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trousers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_trousers_trousers_name'))
        batch_op.drop_index(batch_op.f('ix_trousers_description'))

    op.drop_table('trousers')
    with op.batch_alter_table('shorts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_shorts_shorts_name'))
        batch_op.drop_index(batch_op.f('ix_shorts_description'))

    op.drop_table('shorts')
    with op.batch_alter_table('shirts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_shirts_shirt_name'))
        batch_op.drop_index(batch_op.f('ix_shirts_description'))

    op.drop_table('shirts')
    # ### end Alembic commands ###
