"""added img col

Revision ID: 88db569f6745
Revises: 6fbf586df8eb
Create Date: 2023-11-26 11:55:00.444900

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '88db569f6745'
down_revision = '6fbf586df8eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shirts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quantity', sa.Integer(), nullable=True))

    with op.batch_alter_table('trousers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quantity', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trousers', schema=None) as batch_op:
        batch_op.drop_column('quantity')

    with op.batch_alter_table('shirts', schema=None) as batch_op:
        batch_op.drop_column('quantity')

    # ### end Alembic commands ###
