"""short

Revision ID: b9445d5d54b9
Revises: 20eb2acceaf2
Create Date: 2023-11-25 16:33:23.423126

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b9445d5d54b9'
down_revision = '20eb2acceaf2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shorts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('img', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shorts', schema=None) as batch_op:
        batch_op.drop_column('img')

    # ### end Alembic commands ###
