"""picture column in user

Revision ID: fdd3f94a5811
Revises: 6e82aaa39d0e
Create Date: 2023-11-21 12:15:34.724742

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fdd3f94a5811'
down_revision = '6e82aaa39d0e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile_img', sa.String(length=1440), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('profile_img')

    # ### end Alembic commands ###
